### ISSUE TITLE
Can not be built with recent kernel like 6.2.2

### ISSUE THREAD

**Issue by Pace17881** [pop-os/system76-acpi-dkms#19]
**Distribution (run `cat /etc/os-release`):**
 Debian 12 with kernel 6.2.2
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Can not be built with recent kernel like 6.2.2

**Issue/Bug Description:**

several -Werror=incompatible-pointer-types during make

**Steps to reproduce (if you know):**
pull repo
cd repo
make

**Comment by jackpot51** [comment]
This module was upstreamed a lomg time ago, and is not needed on Linux 6.2. It is provided for use on older kernels.
