### ISSUE TITLE
Tag new release supporting addw3 backlight

### ISSUE THREAD

**Issue by skyl4b** [pop-os/system76-acpi-dkms#30]
Hello, I've just received my first system76 computer, an addw3 laptop, and I'm loving it! I was using it with pop-os just fine, and I tried to install nixos to check it out. 

After the basic installation, I've noticed that, even setting and enabling the [nixos settings for system76 hardware](https://github.com/NixOS/nixpkgs/blob/nixos-23.11/nixos/modules/hardware/system-76.nix), the keyboard backlight still wasn't working. After searching around quite a bit, I've tried to pull the system76-acpi-dkms directly from the master branch, instead of the 1.0.2 (the last tagged release), from 2 years ago, as used in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/1ada32da4ba24d7310653c9ac54888bee463f455/pkgs/os-specific/linux/system76-acpi/default.nix#L3). The master branch seems to have fixed the problem (I suppose because of aaf10e3).

As this is an issue with another distro, I'd like just to ask nicely for a new tagged release if possible, otherwise I'll report the bug to nixpkgs to see how they'd like to handle this. In any case, thank you for all this, my favorite part of open-source software is being able to solve those issues myself :).

(PS: I'm not 100% sure the issue came from here, so if I've made any mistake, please point it out).

**Comment by leviport** [comment]
Which kernel are you running? There was an upstream Linux bug that broke our keyboard backlights: https://bugzilla.kernel.org/show_bug.cgi?id=218045

I believe the upstream fix was merged, but I don't remember which version of 6.6 has the fix. We just patched around it in the 6.6's we were shipping in Pop and Ubuntu.

**Comment by skyl4b** [comment]
I'm running “6.1.69” with the keyboard backlight working

**Comment by ahoneybun** [comment]
@skyl4b if you add this option to your `/etc/nixos/configuration.nix` file then rebuild and reboot you should be on the latest kernel which I think is 6.6.7 (the fix was in the 6.6.5 upstream kernel):

```
boot.kernelPackages = pkgs.linuxPackages_latest;
```


https://gitlab.com/ahoneybun/nix-configs/-/blob/main/configuration.nix?ref_type=heads#L14

**Comment by skyl4b** [comment]
@ahoneybun it worked! Just tried using the latest kernel package, 6.6.8 btw, and the backlight does work without pulling from the master branch here (i removed my overlay to be sure). Thanks a ton for the help!

Will close the issue then :smiley:
