### ISSUE TITLE
Charge control thresholds not exposed in Arch linux.

### ISSUE THREAD

**Issue by jameth** [pop-os/system76-acpi-dkms#6]
**Distribution (run `cat /etc/os-release`):**
 NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Name            : system76-acpi-dkms
Version         : 1.0.2-2
Description     : System76 ACPI Driver (DKMS)
Architecture    : x86_64
URL             : https://github.com/pop-os/system76-acpi-dkms
Licenses        : GPL
Groups          : None
Provides        : None
Depends On      : dkms
Optional Deps   : None
Required By     : None
Optional For    : system76-driver
Conflicts With  : None
Replaces        : None
Installed Size  : 14.32 KiB
Packager        : Unknown Packager
Build Date      : Sun 20 Dec 2020 02:53:56 PM MST
Install Date    : Sun 20 Dec 2020 03:54:34 PM MST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None

**Issue/Bug Description:**
I am running a new System76 lemp10, and have recently installed Arch Linux on it.

I have installed the system76-acpi-dkms package expecting it to enable control of the battery charge thresholds like I am able to do in the factory included Pop.OS install.

For some reason, the charger control thresholds; `/sys/class/power_supply/BAT0/charge_control_start_threshold` and `sys/class/power_supply/BAT0/charge_control_end_threshold` are not showing up on my Arch linux install.

**Steps to reproduce (if you know):**
Install system76-acpi-dkms on Arch linux, try to adjust charge thresholds.

**Expected behavior:**
`/sys/class/power_supply/BAT0/charge_control_start_threshold` and `sys/class/power_supply/BAT0/charge_control_end_threshold` should exist.

**Other Notes:**
I am on a brand new System76 Lemur Pro (lemp10) and this functionality works in Pop.OS

**Comment by sclark13** [comment]
I have the same issue. Installed system76-driver and system76-acpi-dkms on Arch Linux (kernel 5.9.14-arch1-1) on a lemp10 and don't see the charge control thresholds exposed. Although, `dkms status` shows that the system76-acpi module is installed.

**Comment by leviport** [comment]
You'll probably also need [system76-power](https://aur.archlinux.org/packages/system76-power/), but it looks like it'll need to be updated. That version predates the release of the lemp10.

**Comment by jameth** [comment]
Some additional info;

It seems that the module is properly installed to my limited knowledge on this topic;  


    jameth@archlemp \~ :( $ dkms status
    system76, 1.0.11, 5.9.14-arch1-1, x86\_64: installed
    system76-acpi, 1.0.2, 5.9.14-arch1-1, x86\_64: installed (original\_module exists)
    system76-io, 1.0.1, 5.9.14-arch1-1, x86\_64: installed


    jameth@archlemp \~ $ find /lib/modules/\`uname -r\` | grep system76
    /lib/modules/5.9.14-arch1-1/build/include/config/system76
    /lib/modules/5.9.14-arch1-1/build/include/config/system76/acpi.h
    /lib/modules/5.9.14-arch1-1/updates/dkms/system76.ko.xz
    /lib/modules/5.9.14-arch1-1/updates/dkms/system76\_acpi.ko.xz
    /lib/modules/5.9.14-arch1-1/updates/dkms/system76-io.ko.xz


I didn't think I needed system76-power since it just talks mostly about graphics card control, but I will investigate that.

**Comment by electrickite** [comment]
This is likely because the AUR package for `system76-acpi-dkms` tracks the latest tagged release. It seems as though the change control thresholds were added after the last release.

**Comment by jameth** [comment]
electrickite nailed it!

What would it take to get this flagged as a new release?

**Comment by Fire3dderm** [comment]
I wish I knew because I have the same problem

**Comment by yochananmarqos** [comment]
The AUR package has been updated to include https://github.com/pop-os/system76-acpi-dkms/commit/0bc966cf8ec11a173e0bdffb9d5df8d99bea2617 with 1.0.2+1+g0bc966c-1.

**Comment by MilesBHuff** [comment]
This seems to be fixed.
