### ISSUE TITLE
wishlist: any reason why not having the charging threshold compatible with tlp?

### ISSUE THREAD

**Issue by metaphys** [pop-os/system76-acpi-dkms#7]
hi and thanks for your work.
since the last firmware update on lemp9, we can set battery charging threshold. And this is great!
This done via:
/sys/class/power_supply/BAT0/charge_control_start_threshold
/sys/class/power_supply/BAT0/charge_control_end_threshold

I was wondering if this has been done on purpose that it does not match tlp functions that would use:
/sys/class/power_supply/BAT0/charge_start_threshold
/sys/class/power_supply/BAT0/charge_stop_threshold

for people who do not use ubuntu/popos, that would simplify using this functionality. For reference, I was able to use tlp by changing the name of the file used with the 2 followings commands:
sed -i 's/charge_start_threshold/charge_control_start_threshold/g' /usr/share/tlp/func.d/35-tlp-func-batt
sed -i 's/charge_stop_threshold/charge_control_end_threshold/g' /usr/share/tlp/func.d/35-tlp-func-batt

**Distribution (run `cat /etc/os-release`):**
 PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
tlp

**Comment by jacobgkau** [comment]
`charge_control_start_threshold` and `charge_control_stop_threshold` are the standard names defined in the [Linux kernel documentation](https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power).

There is an open issue in the TLP repository for its use of non-standard names here: https://github.com/linrunner/TLP/issues/513
