### ISSUE TITLE
Keyboard colors broken on oryp 6/7

### ISSUE THREAD

**Issue by MilesBHuff** [pop-os/system76-acpi-dkms#8]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
`system76-acpi-dkms 1.0.2+1+g0bc966c-1`

**Issue/Bug Description:**
Setting the keyboard of the oryp7 to anything other than `ffffff` results in completely random colors being assigned.

**Steps to reproduce (if you know):**
```
sudo su -c 'echo 667788 > /sys/class/leds/system76_acpi::kbd_backlight/color'
# Repeat the above ad nauseum
```

**Expected behavior:**
The setting exposed by `system76-acpi-dkms` should use the assigned hex color.

**Other Notes:**
(Added after discussion below) My keyboard brightness is 20%.

**Comment by jacobgkau** [comment]
I'm not seeing this issue on Pop!_OS on an oryp7. `ff0000` sets the color to red, for example. The `667788` example you used sets the color to what looks like a slightly darker white, which makes sense, as that color is nearly equal amounts of each additive primary. (Subtracting some of each color makes the color darker, and setting the color to `000000`/black turns the LEDs off, because they can't express that color.)

Does this work if you boot from a live disk of Pop!_OS?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by jacobgkau** [comment]
Never mind, I do see the colors start to change randomly if I set the color with that command and then turn brightness up or down.

**Comment by MilesBHuff** [comment]
Oh, interesting.  So it's brightness-dependent?  Do you know what the working brightness setting is?

**Comment by jacobgkau** [comment]
> Do you know what the working brightness setting is?

It seems like full brightness is reliable. Maybe this bug has something to do with how the black color is mixed in to lower the brightness. Certain colors (such as plain red) do work, others like `310086` purple are only broken on specific brightness levels.

**Comment by MilesBHuff** [comment]
Interesting.  I've been using a brightness of about 20% -- is this bug reproducible for you as described in my OP when you use that brightness?  Note that you need to send `667788` multiple times to see the bug.

**Comment by leviport** [comment]
Ah yes, it does appear to do the same thing if I have the brightness set lower and I set `667788` repeatedly.

**Comment by MilesBHuff** [comment]
Cool, that's good news -- it means we're all talking about the same bug.
I guys I'll stick with 100% brightness for now, then -- I wrote a program that automatically sets the keyboard color to the average color of the display, and I'm excited to finally see it work, lol.

**Comment by MilesBHuff** [comment]
Reading through the code in https://github.com/pop-os/system76-acpi-dkms/blob/master/system76_acpi.c#L360-L383, it seems as if this bug lies within the BIOS, rather than within `system76-acpi-dkms`.  Should I file this bug there instead?

**Comment by leviport** [comment]
I can transfer the issue for you

**Comment by MilesBHuff** [comment]
Thanks, @leviport!

**Comment by leviport** [comment]
Whoops, I forgot that I can't transfer across organizations. If you could make a new issue in https://github.com/system76/ec and link this issue, that will probably be the best.

**Comment by MilesBHuff** [comment]
Okay!  Will do.

**Comment by MilesBHuff** [comment]
Done.

**Comment by leviport** [comment]
Thanks!
